package platform

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"

	"golang.org/x/crypto/ssh"
)

// GeneratedKey is the artefact of GenerateProfileKey. The caller writes
// PrivateKeyPath into the profile and Passphrase into the OS keyring; the
// PublicKey line is returned so the UI can show it to the user.
type GeneratedKey struct {
	PrivateKeyPath string `json:"privateKeyPath"`
	PublicKey      string `json:"publicKey"`
	Passphrase     string `json:"-"`
}

// GenerateProfileKey creates a fresh Ed25519 keypair encrypted with a
// strong random passphrase. The private key file is written to
// ~/.ssh/pidisk_<safeName>(_N) with 0600 mode; a matching .pub file holds
// the OpenSSH-formatted public key. The Passphrase field is filled with a
// 32-character base64url-encoded random secret.
func GenerateProfileKey(profileName string) (GeneratedKey, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return GeneratedKey{}, err
	}
	sshDir := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return GeneratedKey{}, err
	}

	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return GeneratedKey{}, fmt.Errorf("generate ed25519: %w", err)
	}
	passphrase, err := randomPassphrase(24)
	if err != nil {
		return GeneratedKey{}, err
	}

	safe := SanitizeFileName(profileName)
	if safe == "" {
		safe = "profile"
	}
	keyPath := filepath.Join(sshDir, "pidisk_"+safe)
	for i := 1; fileExists(keyPath); i++ {
		keyPath = filepath.Join(sshDir, fmt.Sprintf("pidisk_%s_%d", safe, i))
	}

	block, err := ssh.MarshalPrivateKeyWithPassphrase(priv, "pidisk:"+safe, []byte(passphrase))
	if err != nil {
		return GeneratedKey{}, fmt.Errorf("encrypt private key: %w", err)
	}
	f, err := os.OpenFile(keyPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return GeneratedKey{}, err
	}
	if err := pem.Encode(f, block); err != nil {
		f.Close()
		_ = os.Remove(keyPath)
		return GeneratedKey{}, err
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(keyPath)
		return GeneratedKey{}, err
	}

	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		return GeneratedKey{}, err
	}
	pubLine := string(ssh.MarshalAuthorizedKey(sshPub))
	if err := os.WriteFile(keyPath+".pub", []byte(pubLine), 0o644); err != nil {
		// the .pub file is informational; we can still return the data
		// even if writing it failed (rare on macOS/Linux). Log path stays.
		_ = err
	}

	return GeneratedKey{
		PrivateKeyPath: keyPath,
		PublicKey:      pubLine,
		Passphrase:     passphrase,
	}, nil
}

func randomPassphrase(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// RemoveAutoGeneratedKey deletes the PIdisk-generated private key file (and
// its matching .pub sibling) at the given path. It is a no-op if the path is
// empty or the file does not look like one we created (basename does not
// start with "pidisk_"), so the caller can hand it any PrivateKeyPath value.
func RemoveAutoGeneratedKey(privateKeyPath string) {
	if privateKeyPath == "" {
		return
	}
	base := filepath.Base(privateKeyPath)
	const prefix = "pidisk_"
	if len(base) <= len(prefix) || base[:len(prefix)] != prefix {
		return
	}
	_ = os.Remove(privateKeyPath)
	_ = os.Remove(privateKeyPath + ".pub")
}
